# Generated by Django 3.0.2 on 2020-12-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('image_url', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
                ('cost', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
    ]
